// Copyright 2006 Nemanja Trifunovic
// Copyright 2011 Jack.arain
/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/


#ifndef UTF8_FOR_CPP_2675DCD0_9480_4C0C_B92A_CC14C027B731
#define UTF8_FOR_CPP_2675DCD0_9480_4C0C_B92A_CC14C027B731

#include <string>

#include <boost/locale.hpp>
#include <boost/locale/utf.hpp>

namespace libyk {

inline std::string wide_utf8(const std::wstring &source);
inline std::wstring utf8_wide(std::string const &source);
inline std::string ansi_utf8(std::string const &source, const std::string &characters = "GB2312");
inline std::string utf8_ansi(std::string const &source, const std::string &characters = "GB2312");
inline std::string wide_ansi(std::wstring const &source, const std::string &characters = "GB2312");
inline std::wstring ansi_wide(const std::string &source, const std::string &characters = "GB2312");

inline std::wstring ansi_wide(const std::string &source, const std::string &characters/* = "GB2312"*/)
{
	std::wstring destination;

	std::string s = ansi_utf8(source, characters);
	destination = boost::locale::conv::utf_to_utf<wchar_t>(s);

	return destination;
}

inline std::string ansi_utf8(std::string const &source, const std::string &characters/* = "GB2312"*/)
{
	std::string destination;

	destination = boost::locale::conv::between(source, "UTF-8", characters);

	return destination;
}

inline std::string wide_utf8(const std::wstring &source)
{
	std::string destination;

	destination = boost::locale::conv::utf_to_utf<char>(source);

	return destination;
}

inline std::wstring utf8_wide(std::string const &source)
{
	std::wstring destination;

	destination = boost::locale::conv::utf_to_utf<wchar_t>(source);

	return destination;
}

inline std::string utf8_ansi(std::string const &source, const std::string &characters/* = "GB2312"*/)
{
	std::string destination;

	destination = boost::locale::conv::between(source, characters, "UTF-8");

	return destination;
}

inline std::string wide_ansi(std::wstring const &source, const std::string &characters/* = "GB2312"*/)
{
	std::string destination;

	destination = wide_utf8(source);
	destination = utf8_ansi(destination, characters);

	return destination;
}

}

#endif // UTF8_FOR_CPP_2675DCD0_9480_4C0C_B92A_CC14C027B731
